### PR TITLE
online backup basic procs

### PR DESCRIPTION
**Pull request by mikra01**
Hi, I added the online backup api and some basic procs

### CODE REVIEW

**Comment by xzfc** [comment]
Hi, thanks for the PR.

Adding bindings to `ndb/wrappers/sqlite3.nim` is OK (nitpick: remove `sqlite3_` prefix to match the naming style).

However, the following concerns regarding `doFullDatabaseBackup`:
1. Can this API be implemented for other DBMS modules (db_postgres, db_mysql, etc)? The plan is to provide similar interface among all modules.
2. The function is not general enough (e.g. can't be used for online backup).

Would it not be better to define it in some extension module inside the user code instead?

**Comment by mikra01** [comment]
ok, I´ll remove the prefix _sqlite_3_

> 1. Can this API be implemented for other DBMS modules (db_postgres, db_mysql, etc)? The plan is to provide similar interface among all modules.

No, database-backup is vendor specific.  I would not recommend to provide a generic API here. The sqlite-jdbc-driver does a pstmt.executeUpdate("restore from ..") but in my personal opinion thats not that nice (it´s not a valid sqlite sql-command nor is it jdbc-standard )
We could flesh out the vendor specific sqlite stuff in a separate module, but I assumed the _sqlite.nim_ module is already at vendor level.
Connection Handling/Pooling, Execute Statements and consuming the resultset could be done within a higher-level generic layer. 
I personally implement something the first time non-generic; and if it´s working you could abstract it further.

> 2\. The function is not general enough (e.g. can't be used for online backup).

sure, you can backup your sqlite instance while there are running transactions on the source database.
The function can be used for backup, restore (both in-memory or file based connections). But I agree the proc name is not nice - _dumpDatabaseInto_ could be a better name) File based sqlite-instances allow multiple connections (within the same process). An in-memory instance needs to be opened with the shared_cache flag to support multiple connections (within the test there are two different in-memory instances). The function blocks till the backup is done.

**Comment by xzfc** [comment]
> We could flesh out the vendor specific sqlite stuff in a separate module, but I assumed the sqlite.nim module is already at vendor level.

Interface of `ndb/sqlite` should match interfaces of other possible `ndb/*` modules. See how interfaces of standard [db_sqlite] and [db_mysql] are almost the same.

[db_sqlite]: https://nim-lang.org/docs/db_sqlite.html
[db_mysql]:https://nim-lang.org/docs/db_mysql.html

Maybe move the function to a new module (like `ndb/sqlite_ex`).

**Comment by mikra01** [comment]
Thank you for your hint. Unfortunately some important objects are not exposed to the common API so there could be some space to evolve...

**Pull request closed without merging**
