### PR TITLE
Add a shortcut for dbValue.

### PR DESCRIPTION
**Pull request by moigagoo**

### CODE REVIEW

**Comment by moigagoo** [comment]
The syntax is discussible, of course.

I'm currently porting Norm from db_sqlite to ndb/sqlite, and I have over a hundred calls to `dbValue` already. I'd be really neat to have a shorter way of converting values to `DbValue`. With `db_sqlite`, I'd use `$value`, so to keep things familiar, I'm proposing `$$value`.

**Comment by moigagoo** [comment]
@xzfc any chance you could review this? It's a tiny PR, should be quick to review (and merge, I hope).

**Comment by xzfc** [comment]
Sorry for the late reply.

Could be this replaced by implicit conversion (using `varargs`) or using `mapLiterals([...], dbValue)`?

I haven't found heavy usage of `dbValue` in norm repo. Perhaps it is intended to be used in user code?

**Comment by moigagoo** [comment]
@xzfc I'm using it in tests when I need to compare rows. Some examples:
- https://github.com/moigagoo/norm/blob/028f9cfa91bcdb77733d5f44c0cc6e52726d4a37/tests/testsqlite.nim#L75
- https://github.com/moigagoo/norm/blob/028f9cfa91bcdb77733d5f44c0cc6e52726d4a37/tests/testrowutils.nim#L17

Unfortunately, implicit conversion can be used only when I'm passing the params as varargs. In my case, I usually pass a Row, so it have to be a homogeneous sequence of DbValue, thus explicit type conversions.

I cannot use mapLiteral too, because again it expects an array, which are homogeneous, and I do not have a homogeneous array at this point, I'm just constructing it.

All in all, dbValue must be used explicitly where I used to use $ explicitly for string conversion. This is why I thought $$ would be a good alias.

**Comment by xzfc** [comment]
> I cannot use mapLiteral too, because again it expects an array, which are homogeneous, and I do not have a homogeneous array at this point, I'm just constructing it.

`mapLiterals` is a macro used to construct an array or seq.

```nim
check dbConn.getAllRows(sql query % "users") == @[
  @[dbValue 0, dbValue "id", dbValue "INTEGER", dbValue 1, dbValue nil, dbValue 1],
  @[dbValue 1, dbValue "email", dbValue "TEXT", dbValue 1, dbValue nil, dbValue 0],
  @[dbValue 2, dbValue "ssn", dbValue "INTEGER", dbValue 0, dbValue nil, dbValue 0],
  @[dbValue 3, dbValue "birthDate", dbValue "INTEGER", dbValue 1, dbValue nil, dbValue 0]
]
```

This could be rewritten as:

```nim
check dbConn.getAllRows(sql query % "users") == mapLiterals(@[
  @[0, "id", "INTEGER", 1, nil, 1],
  @[1, "email", "TEXT", 1, nil, 0],
  @[2, "ssn", "INTEGER", 0, nil, 0],
  @[3, "birthDate", "INTEGER", 1, nil, 0]
], dbValue)
```

But this is probably still cumbersome for smaller arrays. 

---

> The syntax is discussible, of course.

`$$` is already used in the standard library and various others to produce string value.
https://nim-lang.org/docs/marshal.html#%24%24%2CT
Could it be `?$` instead?

**Comment by moigagoo** [comment]
> mapLiterals is a macro used to construct an array or seq.

Thanks, I misread the docs. Sure, this is one way to do it. It doesn't save much typing or make the code more readable though. I'd even suggest it makes the code less readable.

> $$ is already used in the standard library and various others to produce string value.
https://nim-lang.org/docs/marshal.html#%24%24%2CT
Could it be ?$ instead?

Sure, I'm good with it if you are. Maybe plain `?` would do? It's  used in pegs and uri, but it's bound to Peg and Uri types, so we're pretty safe in avoiding a collision.

**Comment by xzfc** [comment]
> Maybe plain `?` would do? It's used in pegs and uri, but it's bound to Peg and Uri types, so we're pretty safe in avoiding a collision.

Sounds good.

**Comment by moigagoo** [comment]
Here's an even better (IMHO) proposal: `!`. Used only in macros where it's deprecated and pegs where it's a low probability collision as with `?`.

I like `!` better, but it's just a subjective thing. Seems weird to put a `?` to convert something to something... `!` is somehow more natural for me, don't know :-)

**Comment by xzfc** [comment]
> Used only in macros where it's deprecated [...]

But it is still exported and takes a string as an argument. This could lead to ambiguity.
I like `?` since it is the same character used as SQL placeholder.

**Comment by moigagoo** [comment]
> I like ? since it is the same character used as SQL placeholder.

Great point, totally agree.

**Comment by moigagoo** [comment]
@xzfc any plans to release this small addition?

**Comment by xzfc** [comment]
done

**Pull request merged**
